apiVersion: v1
kind: ConfigMap
metadata:
  name: taxii-config
  namespace: attack-workbench
data:
  TAXII_ENV: "dev"
  TAXII_APP_ADDRESS: "0.0.0.0"
  TAXII_APP_PORT: "8000"
  TAXII_HTTPS_ENABLED: "false"
  TAXII_SSL_PRIVATE_KEY: ""
  TAXII_SSL_PUBLIC_KEY: ""
  TAXII_CORS_ENABLED: "true"
  TAXII_MAX_CONTENT_LENGTH: "0"
  CERTBOT_LE_FQDN: "localhost"
  CERTBOT_LE_EMAIL: "dev@localhost"
  CERTBOT_LE_ACME_SERVER: "https://acme-staging-v02.api.letsencrypt.org/directory"
  CERTBOT_LE_RSA_KEY_SIZE: "2048"
  TAXII_API_ROOT_PATH: "api"
  TAXII_API_ROOT_TITLE: "ATT&CK Workbench TAXII 2.1 Server (Development)"
  TAXII_API_ROOT_DESCRIPTION: "Development instance of ATT&CK Workbench TAXII 2.1 Server"
  TAXII_CONTACT: "dev@localhost"
  TAXII_CACHE_TYPE: "memcached"
  TAXII_CACHE_HOST: "dev-attack-workbench-taxii-cache"
  TAXII_CACHE_PORT: "11211"
  TAXII_CACHE_TTL: "60"
  TAXII_CACHE_MAX_ITEM_SIZE: "10m"
  TAXII_CACHE_MEM_SIZE: "1024"
  TAXII_CACHE_RECONNECT: "true"
  TAXII_STIX_SRC_URL: "http://dev-attack-workbench-rest-api:3000"
  TAXII_STIX_DATA_SRC: "workbench"
  TAXII_WORKBENCH_AUTH_HEADER: "dGF4aWktc2VydmVyOnNlY3JldC1zcXVpcnJlbA=="
  TAXII_MONGO_URI: "mongodb://dev-attack-workbench-database:27017/taxii"
  TAXII_HYDRATE_ON_BOOT: "true"
  TAXII_LOG_LEVEL: "debug"
  TAXII_LOG_TO_FILE: ""
  TAXII_LOG_TO_HTTP_HOST: ""
  TAXII_LOG_TO_HTTP_PORT: ""
  TAXII_LOG_TO_HTTP_PATH: ""
  TAXII_LOG_TO_SLACK_URL: ""
  TAXII_LOG_TO_SENTRY_DSN: ""